# Generated by Django 5.0.4 on 2024-12-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Email_Id', models.CharField(max_length=100)),
                ('Collage_Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('Area_Of_Intrest', models.CharField(max_length=100)),
            ],
        ),
    ]
